### ISSUE TITLE
Docker build step fails creating dokku user

### ISSUE THREAD

**Issue by rsmithlal** [slypix/minio-dokku#14]
```
Step 2/10 : RUN adduser -D -u 32769 -g dokku dokku
 ---> Running in d302ff953ce1
adduser: group 'dokku' does not exist
remote: The command '/bin/sh -c adduser -D -u 32769 -g dokku dokku' returned a non-zero code: 6
remote: 2021/02/21 18:39:00 exit status 6
```

I managed to get past this step by changing the line in step 2 to `RUN adduser -u 32769 -m -U dokku` but I'm not sure if this is going to break something else down the line. Any ideas?

**Comment by thiago-slb** [comment]
Thanks for the solution, it didn't break anything for me, I was in a hurry so I really needed that! :)

**Comment by haliliceylan** [comment]
i have same problem, i will apply your suggestion thx to much, please merge this pr too :+1:
