### ISSUE TITLE
Setting Nginx headers to avoid invalid headers read errors and increase upload file size

### ISSUE THREAD

**Issue by johnwilson** [slypix/minio-dokku#7]
Hi. Thanks for writing this plugin. I would like to point out a few additional settings that users might want to add in case they run into the [following minio issue](https://github.com/minio/mc/issues/2492). The solution is to set the following configuration on nginx for your minio app: `ignore_invalid_headers off;`. Also in case one would like to increase the max file upload size (to 50mb for example) the following nginx configuration is needed: `client_max_body_size 50m;`. The way to add those settings to your app is specified in the dokku docs [here](http://dokku.viewdocs.io/dokku/configuration/nginx/).

**Comment by mimischi** [comment]
@johnwilson If you're still experiencing the problem, it should be solved now. I'm going to close the issue for now, but feel free to reopen if your problems persist.
